import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from './utils/query-provider';
import './globals.css';
import '../../public/fonts/style.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Clip!',
  description: 'Generated by create next app',
  icons: {
    icon: '/image/clip.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
