name: clip-fe-cd

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install -g npm@10.5.1 --prefix clip
        
      - name: Install next
        run: yarn add next
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

      - name: Install dependencies with yarn
        run: yarn install
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

      - name: Create .env file
        run: |
          cd clip
          echo NEXT_PUBLIC_SERVER_HOST=${{ secrets.SERVER_HOST }} NEXT_PUBLIC_GA_ID=${{ secrets.GA_ID }} NEXT_PUBLIC_NAVER_MAPS_CLIENT_ID=${{ secrets.NAVER_MAPS_CLIENT_ID}} >> .env
          
      - name: Generate build
        run: yarn build --prefix clip

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }} .
        working-directory: ${{ secrets.WORKING_DIRECTORY }}
        
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }}
        
      - name: Access SSH and Docker-Compose run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            cd /home/ubuntu
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }}
            sudo docker-compose down front
            sudo docker-compose up -d front
